name: FYP
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - scikit-learn=0.23.2
  - pandas
  - numpy
  - pillow=9.0.0
  - jupyter
  - tqdm
  - pip:
    - openslide-python